# Generated by Django 2.2 on 2019-12-14 12:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191214_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='user_love', to=settings.AUTH_USER_MODEL),
        ),
    ]
